name: Ansible Setup
 
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches: main
 
jobs:
  ansible-setup:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H benjamin.mancel.takima.cloud >> ~/.ssh/known_hosts
        shell: bash

      - name: Install Ansible
        run: sudo apt install -y ansible

      - name: Run playbook
        run: ansible-playbook -i Ansible/inventories/setup.yml Ansible/playbook.yml
        env:
          ANSIBLE_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
