name: Build and Push Docker Image
 
on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed
    branches: main
 
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
 
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./docker_compose/backend
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest
 
      - name: Build and push database image
        uses: docker/build-push-action@v2
        with:
          context: ./docker_compose/database
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-database:latest
 
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./docker_compose/frontend
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-database:latest